<<<<<<< HEAD
import './globals.css';

import { Work_Sans as WorkSans } from 'next/font/google';

const workSans = WorkSans({ subsets: ['latin'] });

export const metadata = {
  title: 'Adrastos',
  description: 'A killer Backend-as-a-Service (BaaS) written in Rust'
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en" className={workSans.className}>
    <body>{children}</body>
  </html>
);

export default RootLayout;
=======
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
>>>>>>> f05ff050f38d75612d762ec8aee3d88432c28102
