// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutLoginIndexImport } from './routes/_layout/login/index'

// Create Virtual Routes

const DashboardRouteLazyImport = createFileRoute('/dashboard')()
const LayoutRouteLazyImport = createFileRoute('/_layout')()
const DashboardIndexLazyImport = createFileRoute('/dashboard/')()
const LayoutIndexLazyImport = createFileRoute('/_layout/')()
const LayoutSignupLazyImport = createFileRoute('/_layout/signup')()

// Create/Update Routes

const DashboardRouteLazyRoute = DashboardRouteLazyImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/dashboard/route.lazy').then((d) => d.Route),
)

const LayoutRouteLazyRoute = LayoutRouteLazyImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/_layout/route.lazy').then((d) => d.Route))

const DashboardIndexLazyRoute = DashboardIndexLazyImport.update({
  path: '/',
  getParentRoute: () => DashboardRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/dashboard/index.lazy').then((d) => d.Route),
)

const LayoutIndexLazyRoute = LayoutIndexLazyImport.update({
  path: '/',
  getParentRoute: () => LayoutRouteLazyRoute,
} as any).lazy(() => import('./routes/_layout/index.lazy').then((d) => d.Route))

const LayoutSignupLazyRoute = LayoutSignupLazyImport.update({
  path: '/signup',
  getParentRoute: () => LayoutRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/_layout/signup.lazy').then((d) => d.Route),
)

const LayoutLoginIndexRoute = LayoutLoginIndexImport.update({
  path: '/login/',
  getParentRoute: () => LayoutRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/_layout/login/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutRouteLazyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      preLoaderRoute: typeof DashboardRouteLazyImport
      parentRoute: typeof rootRoute
    }
    '/_layout/signup': {
      preLoaderRoute: typeof LayoutSignupLazyImport
      parentRoute: typeof LayoutRouteLazyImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexLazyImport
      parentRoute: typeof LayoutRouteLazyImport
    }
    '/dashboard/': {
      preLoaderRoute: typeof DashboardIndexLazyImport
      parentRoute: typeof DashboardRouteLazyImport
    }
    '/_layout/login/': {
      preLoaderRoute: typeof LayoutLoginIndexImport
      parentRoute: typeof LayoutRouteLazyImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRouteLazyRoute.addChildren([
    LayoutSignupLazyRoute,
    LayoutIndexLazyRoute,
    LayoutLoginIndexRoute,
  ]),
  DashboardRouteLazyRoute.addChildren([DashboardIndexLazyRoute]),
])
