name: adrastos
version: '3.9'

services:
  cockroach:
    image: cockroachdb/cockroach:latest
    profiles:
      - db
    ports:
      - 26257:26257
      - 8080:8080
    command: start-single-node --insecure
    environment:
      - COCKROACH_DATABASE=adrastos
    volumes:
      - cockroach:/cockroach/cockroach-data

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
    profiles:
      - db
    ulimits:
      memlock: -1
    ports:
      - 6379:6379
    volumes:
      - dragonfly:/data

  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    profiles:
      - deploy
    depends_on:
      - app
      - staging-nginx
    env_file:
      - nginx.env
    networks:
      - default
      - staging
    ports:
      - 80:80
      - 443:443
    volumes:
      - letsencrypt:/etc/letsencrypt
      - ./data/nginx/conf.d:/etc/nginx/user_conf.d
      - ./data/nginx/nginxconfig.io:/etc/nginx/nginxconfig.io
      - ./data/letsencrypt/cloudflare.ini:/etc/letsencrypt/cloudflare.ini

  staging-nginx:
    image: nginx:alpine
    restart: unless-stopped
    profiles:
      - deploy
    networks:
      - staging
    ports:
      - 7000:80
    volumes:
      - ./data/staging/nginx.conf:/etc/nginx/nginx.conf
      - ./data/staging/conf.d:/etc/nginx/conf.d
      - ./data/staging/nginxconfig.io:/etc/nginx/nginxconfig.io

  emails:
    image: ghcr.io/xenfo/adrastos-emails:latest
    pull_policy: always
    restart: unless-stopped
    profiles:
      - deploy
    env_file:
      - .env

  app:
    image: ghcr.io/xenfo/adrastos-app:latest
    pull_policy: always
    restart: unless-stopped
    profiles:
      - deploy
    depends_on:
      - emails
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ~/.postgresql/root.crt:/work/certs/cockroach.crt

volumes:
  cockroach:
  dragonfly:
  letsencrypt:

networks:
  staging:
    name: staging
    driver: bridge
