name: adrastos
version: '3.9'

services:
  crdb:
    image: cockroachdb/cockroach:latest
    profiles:
      - db
    ports:
      - 26257:26257
      - 8080:8080
    command: start-single-node --insecure
    environment:
      - COCKROACH_DATABASE=adrastos
    volumes:
      - crdb:/cockroach/cockroach-data

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
    profiles:
      - db
    ulimits:
      memlock: -1
    ports:
      - 6379:6379
    volumes:
      - dragonfly:/data

  app:
    image: ghcr.io/xenfo/adrastos-app:latest
    restart: unless-stopped
    profiles:
      - deploy
    ports:
      - 8000:8000
    volumes:
      - ./certs:/work/certs
      - ~/.postgresql/root.crt:/work/certs/cockroach.crt

  emails:
    image: ghcr.io/xenfo/adrastos-emails:latest
    restart: unless-stopped
    profiles:
      - deploy

  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    env_file:
      - ./nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d

volumes:
  crdb:
  dragonfly:
  nginx_secrets:
