name: adrastos
version: '3.9'

services:
  crdb:
    image: cockroachdb/cockroach:latest
    profiles:
      - db
    ports:
      - 26257:26257
      - 8080:8080
    command: start-single-node --insecure
    environment:
      - COCKROACH_DATABASE=adrastos
    volumes:
      - crdb:/cockroach/cockroach-data

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
    profiles:
      - db
    ulimits:
      memlock: -1
    ports:
      - 6379:6379
    volumes:
      - dragonfly:/data

  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    profiles:
      - deploy
    env_file:
      - deploy.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - letsencrypt:/etc/letsencrypt
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/sites-available:/etc/nginx/sites-available
      - ./data/nginx/nginxconfig.io:/etc/nginx/nginxconfig.io
      - ./data/letsencrypt/cloudflare.ini:/etc/letsencrypt/cloudflare.ini

  app:
    image: ghcr.io/xenfo/adrastos-app:latest
    restart: unless-stopped
    profiles:
      - deploy
    depends_on:
      - nginx
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - letsencrypt:/work/certs
      - ~/.postgresql/root.crt:/work/certs/cockroach.crt

  emails:
    image: ghcr.io/xenfo/adrastos-emails:latest
    restart: unless-stopped
    profiles:
      - deploy
    depends_on:
      - nginx
    env_file:
      - .env

volumes:
  crdb:
  dragonfly:
  letsencrypt:
