name: adrastos
version: '3.9'

services:
  crdb:
    image: cockroachdb/cockroach:latest
    profiles:
      - db
    ports:
      - 26257:26257
      - 8080:8080
    command: start-single-node --insecure
    environment:
      - COCKROACH_DATABASE=adrastos
    volumes:
      - crdb:/cockroach/cockroach-data

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
    profiles:
      - db
    ulimits:
      memlock: -1
    ports:
      - 6379:6379
    volumes:
      - dragonfly:/data

  app:
    image: ghcr.io/xenfo/adrastos-app:latest
    restart: always
    profiles:
      - deploy
    ports:
      - 8000:8000
    volumes:
      - ./certs:/work/certs
      - ~/.postgresql/root.crt:/work/certs/cockroach.crt
    env_file:
      - .env

  emails:
    image: ghcr.io/xenfo/adrastos-emails:latest
    restart: always
    profiles:
      - deploy
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    restart: always
    profiles:
      - deploy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot:latest
    restart: always
    profiles:
      - deploy
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  crdb:
  dragonfly:
