name: adrastos
version: '3.9'

services:
  cockroach:
    image: cockroachdb/cockroach:latest
    profiles:
      - db
    ports:
      - 26257:26257
      - 8080:8080
    command: start-single-node --insecure
    environment:
      - COCKROACH_DATABASE=adrastos
    volumes:
      - cockroach:/cockroach/cockroach-data

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
    profiles:
      - db
    ulimits:
      memlock: -1
    ports:
      - 6379:6379
    volumes:
      - dragonfly:/data

  emails:
    image: ghcr.io/xenfo/adrastos-emails:git
    pull_policy: always
    restart: unless-stopped
    profiles:
      - deploy
    env_file:
      - .env
    networks:
      - deployments_default

  app:
    image: ghcr.io/xenfo/adrastos-app:git
    pull_policy: always
    restart: unless-stopped
    profiles:
      - deploy
    depends_on:
      - emails
    env_file:
      - .env
    networks:
      - deployments_default
    volumes:
      - ~/.postgresql/root.crt:/work/certs/cockroach.crt

volumes:
  cockroach:
  dragonfly:

networks:
  deployments_default:
    external: true
