[package]
name = "adrastos"
version = "0.1.0"
description = "A killer Backend-as-a-Service (BaaS) written in Rust"
authors = ["Samuel Corsi-House <chouse.samuel@gmail.com>"]
license = "AGPL-3.0-or-later"
edition = "2021"

[dependencies]
actix-cors = "0.6.4"
actix-session = { version = "0.7.2", features = ["redis-rs-session"] }
actix-web = { version = "4.3.1", features = ["rustls", "cookies"] }
actix-web-httpauth = "0.8.0"
adrastos_core = { path = "../core" }
argon2 = "0.5.0"
async-trait = "0.1.68"
chrono = "0.4.26"
clap = { version = "4.3.4", features = ["derive"] }
deadpool-postgres = "0.10.5"
deadpool-redis = "0.12.0"
dotenvy = "0.15.7"
fancy-regex = "0.11.0"
futures-util = "0.3.28"
heck = "0.4.1"
json-patch = "1.0.0"
jsonwebtoken = "8.3.0"
lettre = { version = "0.10.4", default-features = false, features = [
	"tokio1-rustls-tls",
	"smtp-transport",
	"pool",
	"hostname",
	"builder",
] }
mailchecker = "5.0.9"
oauth2 = "4.4.1"
regex = "1.8.4"
reqwest = { version = "0.11.18", features = ["json"] }
rustls = "0.20.8"
rustls-pemfile = "1.0.2"
sea-query = { version = "0.29.0-rc.2", features = [
	"attr",
	"with-chrono",
	"postgres-array",
	"thread-safe",
] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.97"
tokio = { version = "1.28.2", features = ["macros"] }
tokio-postgres = { version = "0.7.8", features = [
	"with-chrono-0_4",
	"with-serde_json-1",
] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
utoipa = { version = "3.3.0", features = ["actix_extras", "chrono"] }
utoipa-swagger-ui = { version = "3.1.3", features = ["actix-web"] }
validator = { version = "0.16.1", features = ["derive"] }
