[package]
name = "adrastos_macros"
version = "0.1.0"
authors = ["Samuel Corsi-House <chouse.samuel@gmail.com>"]
license = "AGPL-3.0-or-later"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
deadpool-postgres = "0.10.5"
quote = "1.0.28"
serde_json = "1.0.99"
syn = "2.0.22"
