[package]
name = "adrastos"
version = "0.1.0"
description = "A killer Backend-as-a-Service (BaaS) written in Rust"
authors = ["Samuel Corsi-House <chouse.samuel@gmail.com>"]
license = "AGPL-3.0-or-later"
edition = "2021"

[dependencies]
actix-session = { version = "0.7.2", features = ["redis-actor-session"] }
actix-web = { version = "4.3.1", features = ["openssl", "cookies"] }
actix-web-httpauth = "0.8.0"
argon2 = "0.5.0"
async-trait = "0.1.65"
chrono = "0.4.23"
deadpool-postgres = "0.10.5"
deadpool-redis = "0.11.1"
dotenvy = "0.15.6"
heck = "0.4.1"
json-patch = "0.3.0"
jsonwebtoken = "8.2.0"
# libinjection = "0.3.2"
nanoid = "0.4.0"
oauth2 = "4.3.0"
openssl = "0.10.45"
regex = "1.7.1"
reqwest = { version = "0.11.14", features = ["json"] }
sea-query = { features = [
	"attr",
	"with-chrono",
	"postgres-array",
	"thread-safe"
], git = "https://github.com/SeaQL/sea-query" }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
tokio = { version = "1.26.0", features = ["macros"] }
tokio-postgres = { version = "0.7.7", features = ["with-chrono-0_4", "with-serde_json-1"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
utoipa = { version = "3.0.3", features = ["actix_extras", "chrono"] }
utoipa-swagger-ui = { version = "3.0.2", features = ["actix-web"] }
validator = { version = "0.16.0", features = ["derive"] }
