[package]
name = "adrastos"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.2.1"
deadpool-postgres = "0.10.3"
dotenvy = "0.15.6"
libinjection = "0.3.2"
nanoid = "0.4.0"
regex = "1.7.0"
sea-query = "0.28.1"
serde = { version = "1.0.152", features = ["derive"] }
tokio = { version = "1.23.0", features = ["macros"] }
