[package]
name = "adrastos"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-session = { version = "0.7.2", features = ["redis-actor-session"] }
actix-web = { version = "4.2.1", features = ["openssl"] }
chrono = "0.4.23"
deadpool-postgres = "0.10.3"
deadpool-redis = "0.11.1"
dotenvy = "0.15.6"
libinjection = "0.3.2"
nanoid = "0.4.0"
oauth2 = "4.3.0"
openssl = "0.10.45"
regex = "1.7.0"
sea-query = { version = "0.28.1", features = ["attr"] }
serde = { version = "1.0.152", features = ["derive"] }
tokio = { version = "1.23.0", features = ["macros"] }
