[package]
name = "adrastos_core"
version = "0.1.0"
authors = ["Samuel Corsi-House <chouse.samuel@gmail.com>"]
license = "AGPL-3.0-or-later"
edition = "2021"

[dependencies]
actix-web = { version = "4.3.1", features = ["openssl", "cookies"] }
argon2 = "0.5.0"
async-trait = "0.1.68"
chrono = "0.4.24"
deadpool-postgres = "0.10.5"
deadpool-redis = "0.12.0"
fancy-regex = "0.11.0"
heck = "0.4.1"
json-patch = "1.0.0"
jsonwebtoken = "8.3.0"
nanoid = "0.4.0"
oauth2 = "4.4.0"
openssl = "0.10.52"
postgres-openssl = "0.5.0"
rand = "0.8.5"
regex = "1.8.3"
reqwest = { version = "0.11.18", features = ["json"] }
sea-query = { version = "0.29.0-rc.2", features = [
	"attr",
	"with-chrono",
	"postgres-array",
	"thread-safe",
] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
tokio = { version = "1.28.2", features = ["macros"] }
tokio-postgres = { version = "0.7.8", features = [
	"with-chrono-0_4",
	"with-serde_json-1",
] }
totp-rs = { version = "5.0.2", features = ["gen_secret", "qr"] }
tracing = "0.1.37"
utoipa = { version = "3.3.0", features = ["actix_extras", "chrono"] }
validator = { version = "0.16.0", features = ["derive"] }
