[package]
name = "core"
version = "0.1.0"
authors = ["Samuel Corsi-House <chouse.samuel@gmail.com>"]
license = "AGPL-3.0-or-later"
edition = "2021"

[dependencies]
actix-web = { version = "4.3.1", features = ["openssl", "cookies"] }
argon2 = "0.5.0"
async-trait = "0.1.68"
chrono = "0.4.24"
deadpool-postgres = "0.10.5"
deadpool-redis = "0.11.1"
fancy-regex = "0.11.0"
heck = "0.4.1"
json-patch = "0.3.0"
jsonwebtoken = "8.3.0"
libinjection = "0.3.2"
nanoid = "0.4.0"
oauth2 = "4.3.0"
openssl = "0.10.48"
regex = "1.7.3"
reqwest = { version = "0.11.15", features = ["json"] }
sea-query = { version = "0.29.0-rc.1", features = [
	"attr",
	"with-chrono",
	"postgres-array",
	"thread-safe"
] }
serde = { version = "1.0.158", features = ["derive"] }
serde_json = "1.0.94"
tokio = { version = "1.26.0", features = ["macros"] }
tokio-postgres = { version = "0.7.7", features = [
	"with-chrono-0_4",
	"with-serde_json-1"
] }
tracing = "0.1.37"
utoipa = { git = "https://github.com/juhaku/utoipa", features = [
	"actix_extras",
	"chrono"
] }
validator = { version = "0.16.0", features = ["derive"] }
