name: CD

on:
  push:
    tags: ["*"]
    branches: [main]
  pull_request:
    types: [opened, closed]
  issue_comment:
    types: [edited]

jobs:
  # git:
  #   name: Git
  #   runs-on: ubuntu-latest
  #   environment: Backend Production
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'

  #   steps:
  #     - uses: actions/checkout@v3

  #     - uses: docker/login-action@v2
  #       with:
  #         registry: ghcr.io
  #         username: Xenfo
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #     - uses: docker/setup-buildx-action@v2

  #     - uses: dtolnay/rust-toolchain@nightly
  #     - run: cargo build --release

  #     - name: Build and push the app image
  #       uses: docker/build-push-action@v4
  #       with:
  #         push: true
  #         context: .
  #         file: .github/deploy/Dockerfile.app
  #         tags: ghcr.io/xenfo/adrastos-app:git

  #     - name: Build and push the worker image
  #       uses: docker/build-push-action@v4
  #       with:
  #         push: true
  #         file: .github/deploy/Dockerfile.emails
  #         tags: ghcr.io/xenfo/adrastos-emails:git

  staging-init:
    name: Staging Init
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'opened'

    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Backend Staging
            - [ ] Deploy this PR

  staging:
    name: Staging
    runs-on: ubuntu-latest
    environment: Backend Preview
    if: github.event_name == 'issue_comment' && github.event.issue.pull_request && github.event.comment.user.id == 41898282 && contains(github.event.comment.body, '- [x] Deploy this PR') && github.event.issue.state == 'open'

    permissions:
      contents: read
      packages: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - run: git fetch origin pull/${{ github.event.issue.number }}/head
      - run: git checkout FETCH_HEAD

      - name: Update comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ github.event.comment.id }}
          edit-mode: replace
          body: |
            ## Backend Staging
            Status: **[DEPLOYING](https://github.com/Xenfo/adrastos/actions/runs/${{ github.run_id }}) :hourglass:**
            - [ ] Deploy this PR

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: Xenfo
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2

      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo build --release

      - name: Build and push the app image
        uses: docker/build-push-action@v4
        id: app
        with:
          push: true
          context: .
          file: .github/deploy/Dockerfile.app
          tags: ghcr.io/xenfo/adrastos-app:staging-pr-${{ github.event.issue.number }}

      - name: Build and push the worker image
        uses: docker/build-push-action@v4
        id: emails
        with:
          push: true
          file: .github/deploy/Dockerfile.emails
          tags: ghcr.io/xenfo/adrastos-emails:staging-pr-${{ github.event.issue.number }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          username: root
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd adrastos
            ./scripts/staging.sh cou ${{ github.event.issue.number }} $(gh pr view 32 --json headRefName -q .headRefName)

      - name: Update comment
        uses: peter-evans/create-or-update-comment@v3
        if: always()
        with:
          comment-id: ${{ github.event.comment.id }}
          edit-mode: replace
          body: |
            ## Backend Staging
            Status: **[${{ contains(steps.*.conclusion, 'success') && 'SUCCEEDED' || contains(steps.*.conclusion, 'failure') && 'FAILED' || 'CANCELLED' }}](https://github.com/Xenfo/adrastos/actions/runs/${{ github.run_id }}) ${{ contains(steps.*.conclusion, 'success') && ':white_check_mark:' || contains(steps.*.conclusion, 'failure') && ':x:' || ':grey_question:' }}**
            - [ ] Deploy this PR

  staging-end:
    name: Staging End
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed'

    steps:
      - name: Remove from VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          username: root
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd adrastos
            ./scripts/staging.sh destroy ${{ github.event.issue.number }}

  # release:
  #   name: Release
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'push' && github.ref == 'refs/tags/v*'

  #   steps:
  #     - uses: actions/checkout@v3

  #     - uses: docker/login-action@v2
  #       with:
  #         registry: ghcr.io
  #         username: Xenfo
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #     - uses: docker/setup-buildx-action@v2

  #     - uses: dtolnay/rust-toolchain@nightly
  #     - run: cargo build --release

  #     - run: |
  #         echo "VERSION=\"$(echo ${{ github.ref_name }} | sed 's/v//')\"" >> $GITHUB_OUTPUT
  #       id: version

  #     - name: Build and push the app image
  #       uses: docker/build-push-action@v4
  #       with:
  #         push: true
  #         context: .
  #         file: .github/deploy/Dockerfile.app
  #         tags: ghcr.io/xenfo/adrastos-app:latest,ghcr.io/xenfo/adrastos-app:${{ github.ref_name }}

  #     - name: Build and push the worker image
  #       uses: docker/build-push-action@v4
  #       with:
  #         push: true
  #         file: .github/deploy/Dockerfile.emails
  #         tags: ghcr.io/xenfo/adrastos-emails:latest,ghcr.io/xenfo/adrastos-emails:${{ steps.version.outputs.VERSION }}
