name: CI Rust

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy
      - run: mkdir packages/dashboard/dist

      - name: Check formatting
        run: cargo fmt --check

      - name: Check Clippy
        run: cargo clippy --all-targets --locked

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - run: mkdir packages/dashboard/dist

      - name: Test the project
        run: cargo test --all-targets --locked
