name: CI TypeScript

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: jdxcode/rtx-action@v1
      - run: yarn install --immutable

      - name: Lint the project
        run: yarn lint
