name: CI TypeScript

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: jdx/mise-action@v2
      - run: pnpm install

      - name: Check the project
        run: pnpm check
