name: CI TypeScript

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: jdx/mise-action@v2
      - run: corepack enable
      - run: yarn install --immutable
      - run: cd packages/lib && yarn build

      - name: Lint the project
        run: yarn lint
