name: Docker

on:
  push:
    tags: ["*"]
    branches: [main]
  pull_request:

jobs:
  # git:
  #   name: Git
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'

  #   steps:
  #     - uses: actions/checkout@v3

  staging:
    name: Staging
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: Xenfo
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
      # - uses: docker/build-push-action@v4

  # release:
  #   name: Release
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/tags/v*'

  #   steps:
  #     - uses: actions/checkout@v3
