name: Docker

on:
  push:
    tags: ["*"]
    branches: [main]
  pull_request:

jobs:
  # git:
  #   name: Git
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'

  #   steps:
  #     - uses: actions/checkout@v3

  staging:
    name: Staging
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: Xenfo
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2

      - name: Build and push the app image
        uses: docker/build-push-action@v4
        with:
          push: true
          file: crates/app/Dockerfile
          tags: ghcr.io/xenfo/adrastos-app:staging-pr-${{ github.event.pull_request.number }}

      - name: Build and push the worker image
        uses: docker/build-push-action@v4
        with:
          push: true
          file: packages/emails/Dockerfile
          tags: ghcr.io/xenfo/adrastos-emails:staging-pr-${{ github.event.pull_request.number }}

  # release:
  #   name: Release
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/tags/v*'

  #   steps:
  #     - uses: actions/checkout@v3
