name: Docker

on:
  push:
    tags: ["*"]
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  git:
    name: Git
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: Xenfo
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2

      - name: Build and push the app image
        uses: docker/build-push-action@v4
        with:
          push: true
          file: crates/app/Dockerfile
          tags: ghcr.io/xenfo/adrastos-app:git

      - name: Build and push the worker image
        uses: docker/build-push-action@v4
        with:
          push: true
          file: packages/emails/Dockerfile
          tags: ghcr.io/xenfo/adrastos-emails:git

  staging:
    name: Staging
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: Xenfo
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2

      - name: Build and push the app image
        uses: docker/build-push-action@v4
        with:
          push: true
          file: crates/app/Dockerfile
          tags: ghcr.io/xenfo/adrastos-app:staging-pr-${{ github.event.pull_request.number }}

      - name: Build and push the worker image
        uses: docker/build-push-action@v4
        with:
          push: true
          file: packages/emails/Dockerfile
          tags: ghcr.io/xenfo/adrastos-emails:staging-pr-${{ github.event.pull_request.number }}

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/tags/v*'

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: Xenfo
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2

      - run: |
          echo ${{ github.ref_name }} | sed 's/v//' >> $GITHUB_OUTPUT
        id: version

      - name: Build and push the app image
        uses: docker/build-push-action@v4
        with:
          push: true
          file: crates/app/Dockerfile
          tags: ghcr.io/xenfo/adrastos-app:latest,ghcr.io/xenfo/adrastos-app:${{ github.ref_name }}

      - name: Build and push the worker image
        uses: docker/build-push-action@v4
        with:
          push: true
          file: packages/emails/Dockerfile
          tags: ghcr.io/xenfo/adrastos-emails:latest,ghcr.io/xenfo/adrastos-emails:${{ github.ref_name }}
